url: https://crownstack.com
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["CNAME", "README.md", "Rakefile", "generate.rb", "Gemfile", "Gemfile.lock"]
include: ["_pages"]
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
